<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZia8tcf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZia8tcf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZia8tcf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZia8tcf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZia8tcf\appDevDebugProjectContainer([
    'container.build_hash' => 'Zia8tcf',
    'container.build_id' => '930052cd',
    'container.build_time' => 1666365056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZia8tcf');
